//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mvcStok2.Models.Entity
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MVCStokEntities2 : DbContext
    {
        public MVCStokEntities2()
            : base("name=MVCStokEntities2")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<KATEGORILER> KATEGORILER { get; set; }
        public virtual DbSet<MUSTERILER> MUSTERILER { get; set; }
        public virtual DbSet<SATISLAR> SATISLAR { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<URUNLER> URUNLER { get; set; }
    }
}
